#!/bin/bash
#
#   Requires mutt, gcloud with gsutil 
#   mac: brew install mutt
#   linux sudo apt install mutt
#
#       mutt setup: ~/.muttrc


gsutil -m cp -r -n gs://test-lab-vs5fwd255p258-y231pa7vdj4mx .
python pythonParser.py test-lab-vs5fwd255p258-y231pa7vdj4mx
echo "Sending csv-file to andvre@solutionxperts.se" | mutt -s "Updated csv file" -a test.csv -- andvre@solutionxperts.se