#!/bin/bash
#
#   Requires mutt, gcloud with gsutil 
#   mac: brew install mutt
#   linux sudo apt install mutt
#
#       mutt setup: ~/.muttrc


gsutil -m cp -r -n gs://test-lab-vs5fwd255p258-y231pa7vdj4mx .
# python pythonParser.py test-lab-vs5fwd255p258-y231pa7vdj4mx
python3 multiThreadedpythonParser.1.py test-lab-vs5fwd255p258-y231pa7vdj4mx
echo "Sending csv-file to dersi_91@hotmail.com" | mutt -s "Updated csv file" -a test.csv -- dersi_91@hotmail.com

